---
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: flake8
      - id: mixed-line-ending
        args: [--fix=lf]
        exclude: '\.bat$'
      - id: pretty-format-json
        args: [--autofix]
      - id: trailing-whitespace

-   repo: git://github.com/doublify/pre-commit-clang-format
    sha: master
    hooks:
      -   id: clang-format
          name: clang-format
          description: Format files with ClangFormat.
          entry: clang-format
          language: system
          files: \.(c|cc|cxx|cpp|frag|glsl|h|hpp|hxx|ih|ispc|ipp|java|js|m|proto|vert)$
          args: ['-style=file', '-i']

-   repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
      - id: dockerfilelint
        stages: [commit]

-   repo: git://github.com/detailyang/pre-commit-shell
    rev: 1.0.4
    hooks:
      - id: shell-lint

-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
      - id: black
        language_version: python3.6
